### ISSUE TITLE
Bought book but have not received it

### ISSUE THREAD

**Issue by JamesCropcho** [troymott/bulma-book-code#18]
Hello:

I hope this message finds you well.

Twenty-four hours ago I purchased a copy of this book from the publisher, but I have yet to receive it. Twenty-three hours ago I sent a message to the publisher via the contact form; I haven't heard back. The publisher does not have a published email address for me to follow up with. I'm sure this is not the absolute best venue for me to make contact about this issue, but it seems to be the best option actually available to me.

Can you help me get a copy of your book?

Regards,
James Cropcho

**Comment by troymott** [comment]
Thanks James, I will get you the files later today.

--Troy
